language: java

jdk:
  - openjdk6
  
before_install:
  - "source <(curl -H 'Cache-Control: no-cache' -s https://raw.githubusercontent.com/tamura-orz/travisci-tools/master/common/travis.sh)"
  - chmod +x gradlew
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - echo ${REPO_USER}
  - echo ${DEVELOP_REPO_URL} 
  - echo ${DEPLOY_HOST_URL} 
  - echo ${DEPLOY_REPO_NAME}
  
script:
  - ./gradlew uploadArchives -PnablarchRepoUsername=${REPO_USER} -PnablarchRepoPassword=${DEPLOY_PASSWORD} -PnablarchRepoReferenceUrl=${DEVELOP_REPO_URL} -PnablarchRepoDeployUrl=${DEPLOY_HOST_URL} -PnablarchRepoName=${DEPLOY_REPO_NAME} --no-daemon

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
